pygments: true

name: 'Kirinyan'
tagline: ''
future: false
timezone: Australia/Sydney

baseurl: http://kirinyan.net

permalink: /:title/
assets: https://dl.dropboxusercontent.com/u/158866275

paginate: 10
